import { Ingredient } from 'entities/ingredient';

export const data: Ingredient[] = [
    {
    id: "643d69a5c3f7b9001cfa093d",
    name: "Флюоресцентная булка R2-D3",
    type: "bun",
    proteins: 44,
    fat: 26,
    carbohydrates: 85,
    calories: 643,
    price: 988,
    image: "https://code.s3.yandex.net/react/code/bun-01.png",
    imageMobile: "https://code.s3.yandex.net/react/code/bun-01-mobile.png",
    imageLarge: "https://code.s3.yandex.net/react/code/bun-01-large.png",
  },
  {
    id: "643d69a5c3f7b9001cfa0941",
    name: "Биокотлета из марсианской Магнолии",
    type: "main",
    proteins: 420,
    fat: 142,
    carbohydrates: 242,
    calories: 4242,
    price: 424,
    image: "https://code.s3.yandex.net/react/code/meat-01.png",
    imageMobile: "https://code.s3.yandex.net/react/code/meat-01-mobile.png",
    imageLarge: "https://code.s3.yandex.net/react/code/meat-01-large.png",
  },
  {
    id: "643d69a5c3f7b9001cfa093e",
    name: "Филе Люминесцентного тетраодонтимформа",
    type: "main",
    proteins: 44,
    fat: 26,
    carbohydrates: 85,
    calories: 643,
    price: 988,
    image: "https://code.s3.yandex.net/react/code/meat-03.png",
    imageMobile: "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
    imageLarge: "https://code.s3.yandex.net/react/code/meat-03-large.png",
  },
  {
    id: "643d69a5c3f7b9001cfa0943",
    name: "Соус фирменный Space Sauce",
    type: "sauce",
    proteins: 50,
    fat: 22,
    carbohydrates: 11,
    calories: 14,
    price: 80,
    image: "https://code.s3.yandex.net/react/code/sauce-04.png",
    imageMobile: "https://code.s3.yandex.net/react/code/sauce-04-mobile.png",
    imageLarge: "https://code.s3.yandex.net/react/code/sauce-04-large.png",
  },
  {
    id: "643d69a5c3f7b9001cfa0940",
    name: "Говяжий метеорит (отбивная)",
    type: "main",
    proteins: 800,
    fat: 800,
    carbohydrates: 300,
    calories: 2674,
    price: 3000,
    image: "https://code.s3.yandex.net/react/code/meat-04.png",
    imageMobile: "https://code.s3.yandex.net/react/code/meat-04-mobile.png",
    imageLarge: "https://code.s3.yandex.net/react/code/meat-04-large.png",
  },
  {
    id: "643d69a5c3f7b9001cfa0944",
    name: "Соус традиционный галактический",
    type: "sauce",
    proteins: 42,
    fat: 24,
    carbohydrates: 42,
    calories: 99,
    price: 15,
    image: "https://code.s3.yandex.net/react/code/sauce-03.png",
    imageMobile: "https://code.s3.yandex.net/react/code/sauce-03-mobile.png",
    imageLarge: "https://code.s3.yandex.net/react/code/sauce-03-large.png",
  },
  {
    id: "643d69a5c3f7b9001cfa0945",
    name: "Соус с шипами Антарианского плоскоходца",
    type: "sauce",
    proteins: 101,
    fat: 99,
    carbohydrates: 100,
    calories: 100,
    price: 88,
    image: "https://code.s3.yandex.net/react/code/sauce-01.png",
    imageMobile: "https://code.s3.yandex.net/react/code/sauce-01-mobile.png",
    imageLarge: "https://code.s3.yandex.net/react/code/sauce-01-large.png",
  },
  {
    id: "643d69a5c3f7b9001cfa0946",
    name: "Хрустящие минеральные кольца",
    type: "main",
    proteins: 808,
    fat: 689,
    carbohydrates: 609,
    calories: 986,
    price: 300,
    image: "https://code.s3.yandex.net/react/code/mineral_rings.png",
    imageMobile: "https://code.s3.yandex.net/react/code/mineral_rings-mobile.png",
    imageLarge: "https://code.s3.yandex.net/react/code/mineral_rings-large.png",
  },
  {
    id: "643d69a5c3f7b9001cfa094a",
    name: "Сыр с астероидной плесенью",
    type: "main",
    proteins: 84,
    fat: 48,
    carbohydrates: 420,
    calories: 3377,
    price: 4142,
    image: "https://code.s3.yandex.net/react/code/cheese.png",
    imageMobile: "https://code.s3.yandex.net/react/code/cheese-mobile.png",
    imageLarge: "https://code.s3.yandex.net/react/code/cheese-large.png",
  }
]
